super_login.settings:
  type: config_object
  mapping:
    super_login:
      type: config_object
      label: 'Super Login Configuration'
      mapping:
        login_text:
          type: label
          label: 'Login Text'
        forgot_pw_text:
          type: label
          label: 'Forgot Password Text'
        capslock_msg:
          type: label
          label: 'Caps Lock Message'
        new_account_text:
          type: label
          label: 'New Account Text'
        login_title:
          type: label
          label: 'Login Title'
        password_reset_title:
          type: label
          label: 'Password Reset Title'
        back_link:
          type: label
          label: 'Back Link Text'
        messages:
          type: boolean
          label: 'Messages'
        css:
          type: boolean
          label: 'CSS'
        button_theme:
          type: boolean
          label: 'Button Theme'
        placeholder:
          type: boolean
          label: 'Placeholder'
        autofocus:
          type: boolean
          label: 'Autofocus'
        login_type:
          type: integer
          label: 'Login Type'
        capslock:
          type: boolean
          lable: 'Display Caps Lock Message'
        login_placeholder:
          type: label
          label: 'Login Placeholder'
        pass_placeholder:
          type: label
          label: 'Password Placeholder'
